### ISSUE TITLE
Add KANAGAWA to the collection.

### ISSUE THREAD

**Issue by josepheiba** [kovidgoyal/kitty-themes#106]
Please, include KANAGAWA in the collection. You can find it here: https://github.com/rebelot/kanagawa.nvim

https://github.com/rebelot/kanagawa.nvim/blob/master/extras/kanagawa.conf
https://github.com/rebelot/kanagawa.nvim/blob/master/extras/kanagawa_dragon.conf
https://github.com/rebelot/kanagawa.nvim/blob/master/extras/kanagawa_light.conf

Question: When I change the theme using kitten, the 'macos_titlebar_color' always get commented out by '#', is this intentional?

**Comment by kovidgoyal** [comment]
You are welcome to send a PR adding them. And yes chaging a theme means
all exisintg color telated settings are commented out, since it is
assumend they are being managed by the theme. You can avoif this by
using --config-file-name with the kitten.

**Comment by josepheiba** [comment]
thank you
