### ISSUE TITLE
How can I leave the selection window?

### ISSUE THREAD

**Issue by ShelpAm** [kovidgoyal/kitty-themes#114]

**Comment by ShelpAm** [comment]
After I reopen the window, the problem disappeared! Thanks for your working!

**Comment by thiswillbeyourgithub** [comment]
I think I have the same issue. For some reason I pressing enter or escape does nothing and I can't leave.

I notice this in my journalctl -f logs that appear as soon as I force close the terminal:
`Application escape mode is not supported, the extended keyboard protocol should be used instead`

**Comment by thiswillbeyourgithub** [comment]
Fix: that just started happening when I manually upgraded kitty from a very old ubuntu version to the latest, and apparently the fix is to git clone kitty-themes again and put it instead of the old one in .config/kitty/kitty-themes

**Comment by ShelpAm** [comment]
The same here: `Application escape mode is not supported, the extended keyboard protocol should be used instead`. This happens while using `tmux`.

**Comment by thiswillbeyourgithub** [comment]
Yes I just noticed too its because of tmux. After reading about it I decided to start migrating from tmux to kitty.

Here are helpful links:
https://github.com/kovidgoyal/kitty/issues/2422
https://github.com/nobe4/dotfiles/issues/21
https://github.com/lucasteligioridis/dot-files/issues/1

**Comment by ShelpAm** [comment]
@thiswillbeyourgithub Thank you very much! These really help me a lot!
