### ISSUE TITLE
comments out the "macos_titlebar_color" line in kitty.conf

### ISSUE THREAD

**Issue by habahabahaba** [kovidgoyal/kitty-themes#120]
Hello and thank you for your work.
Is there any way to prevent "kitty +kitten themes" from commenting out the "macos_titlebar_color" line in the kitty.conf file every time I change a theme ("enter" -> "m")?

**Comment by kovidgoyal** [comment]
put it in a separate conf file and include it into kitty.conf

**Comment by habahabahaba** [comment]
Thank you!
