### ISSUE TITLE
Easy way to add a new theme to the previewer?

### ISSUE THREAD

**Issue by lkoning** [kovidgoyal/kitty-themes#17]
Off course it's not a lot of work to preview a theme by just importing the theme file into the kitty.conf. But it would be really convenient if one could preview the newly added themefile in the previewer openen by `kitty +kitten themes`. 

I tried by manually updaring the zipfile in ~/.cache/kitty to no avail. The python code does something with a comment to the downloaded zipfile? Using '--cache-age -1' did not stop it from downloading from Github again. 

Could you add a procedure to the readme file for this? And maybe add a command line option to load additional theme files?

Thank you, appreciate your work.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/themes/#using-your-own-themes
