### ISSUE TITLE
Vim theme integration?

### ISSUE THREAD

**Issue by zkamvar** [kovidgoyal/kitty-themes#20]
I am curious: is there a vim function that can mirror the current kitty theme? 

Right now, I have a rudimentary function that [switches between papercolor light and dark based on the background of my kitty instance](https://github.com/zkamvar/config-files/blob/52d47c51e44951cb4fa0ac3e20fe6233dda6848e/.vimrc#L158-L187), but I suspect that one could also pass the values from the kitty theme to vim in a similar manner.

**Comment by kovidgoyal** [comment]
None that I know of. vim themes and terminal themes are not really
directly equivalent, vim has a bunch of syntax and other special colors.
Terminal themes have 16 basic colors and a bunch of UI colors. You cant really map
automatically from the one to the other.

**Comment by ismay** [comment]
You could use the theme mentioned in this post: https://jeffkreeftmeijer.com/vim-16-color/. It uses only the 16 ansi colors for the vim theme, which means it’ll adapt automatically to your kitty theme.
