### ISSUE TITLE
AtomOneLight selection colors are wrong

### ISSUE THREAD

**Issue by flipflop133** [kovidgoyal/kitty-themes#25]
The current selection combination colors are:
```
selection_foreground #f8f8f8
selection_background #ececec
```
![image](https://user-images.githubusercontent.com/48946818/147835198-c2ca60ac-3b22-4be2-ba9c-c20356c9d6c3.png)
which offer a terrible contrast (1.11:1 according to [WebAim](https://webaim.org/resources/contrastchecker/)).
I checked VS Code [AtomOneLight](https://github.com/akamud/vscode-theme-onelight/blob/master/themes/OneLight.json) color combination and colors should be:
```
selection_foreground #2a2b33
selection_background #e5e5e6
```
![image](https://user-images.githubusercontent.com/48946818/147835174-eec6df50-2f99-414b-a5c0-9a466f906ac9.png)
which offer a way better contrast (11.18:1).

**Comment by kovidgoyal** [comment]
Feel free to send a PR fixing it, looks OK to me.
