### ISSUE TITLE
No kitten named themes: Upgrading/reinstalling doesn't help

### ISSUE THREAD

**Issue by VBPROGER** [kovidgoyal/kitty-themes#67]
Hello, I have a problem.
I've recently installed kitty and when I try to
access the themes configuration, it fails.
Output:
```bash
┬─[vbproger@pc:~]─[22:43:41]
╰─>$ kitty +kitten themes
Available builtin kittens:
icat
broadcast
show_key
clipboard
ask
remote_file
show_error
hints
unicode_input
ssh
query_terminal
resize_window
hyperlinked_grep
diff
choose
panel
No kitten named themes
┬─[vbproger@pc:~]─[22:43:45]
╰─>$ kitty +kitten themes
```
The shell I'm using is fish.
<br>
*`uname`* output:
```
┬─[vbproger@pc:~]─[22:44:32]
╰─>$ uname -a
Linux pc 5.15.0-50-lowlatency #56-Ubuntu SMP PREEMPT Wed Sep 21 13:57:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
# What I've tried
I've try using these commands:
- `sudo apt install kitty --reinstall`
- `sudo apt install kitty --upgrade`
- `sudo apt upgrade kitty`
but none of them works.
Please help me!

**Comment by kovidgoyal** [comment]
Do not use distro packages. use the official kitty binaries.
https://sw.kovidgoyal.net/kitty/binary/
