### ISSUE TITLE
modus_operandi text not visible

### ISSUE THREAD

**Issue by secomi** [kovidgoyal/kitty-themes#68]
Hello when using the light theme Modus_Operandi, some text is not visible. With light theme shouldn't color0 and color15 be inverted ? 

Here an example showing the Unicode interface: CTRL+SHIFT+u
![modus_operandi_text_not_visible](https://user-images.githubusercontent.com/29351844/199067809-055f1f92-f067-42b7-9d11-20659d5a4eb8.png)

Where we can see that the text is "here":
![kitty-text-selected](https://user-images.githubusercontent.com/29351844/199067962-772c8240-a46a-42e7-aa9a-6a0be6d7cc24.png)

Or is there a "flag" which defines a light theme and will invert the defined colors?

**Comment by kovidgoyal** [comment]
I'm afraid I don't maintain these themes, they are contributed by their
creators or copied from upstream, you would need to contact the creator
of the theme to discuss changes to it. 

And no there is no flag, the colors are used directly.
