### ISSUE TITLE
keyboard doesn't work

### ISSUE THREAD

**Issue by realtica** [kovidgoyal/kitty-themes#72]
kitty 0.26.4 (fresh installation, all keyboard features works fine)

None of all options keyboard works like Enter, Find(/), and nothing happened for filters like Dark, Recent, etc(with mouse or keyboard).

**Comment by kovidgoyal** [comment]
Works fine for me with up-to-date kitty.

**Comment by realtica** [comment]
> Works fine for me with up-to-date kitty.

Thanks for nothing.

**Comment by ShelpAm** [comment]
The same here
