### ISSUE TITLE
dir color visible in c64 theme

### ISSUE THREAD

**Issue by mcfiredrill** [kovidgoyal/kitty-themes#82]
The blue for dir colors is not visible for me. Any fix? 
![line_20230531_200129](https://github.com/kovidgoyal/kitty-themes/assets/66243/90bc0439-7b3f-4d7e-888f-446c34689f97)

**Comment by kovidgoyal** [comment]
This repo simply acts as centralised storage for themes. If you have issues with a theme report it to the creator of the theme.

**Comment by mcfiredrill** [comment]
Alright, maybe it would help if this issue template could state that as well?
https://github.com/kovidgoyal/kitty-themes/blob/master/.github/ISSUE_TEMPLATE/theme-issue.md
